### ISSUE TITLE
Download Link Only on home page

### ISSUE THREAD

**Issue by miklb** [habari/hpo#13]
I suggest having a link to download either in the sticky header or in the footer. If someone comes to the site for the 1st time, they may click around a bit before deciding to try it/download. As it stands now, the only link to the download page is on the home page.

**Comment by chrisjdavis** [comment]
There is a download link on almost every page, on some pages twice. The grey bar has a download item as its first member. 

![Screen Shot 2013-04-03 at 4 04 58 PM](https://f.cloud.github.com/assets/867449/336251/2dcb7c9e-9ca2-11e2-92a0-8a86e486e053.png)

**Comment by miklb** [comment]
doh. I even raised an issue about the hover on those icons too.
