### ISSUE TITLE
Icon hover issues

### ISSUE THREAD

**Issue by miklb** [habari/hpo#2]
The download, source code, manual and community icons when hovered have a different behavior than on the home page and developer page. The icons switch to white with an orange square. Assuming they are picking up styling from other icon hovers.

**Comment by chrisjdavis** [comment]
Wait, the quicklinks toolbar has a hover state for you? They aren't supposed to. I am confus-ed.

**Comment by ringmaster** [comment]
http://screencast.com/t/XJkqw382i  It's not on the homepage, but on interior pages, like Support.

**Comment by chrisjdavis** [comment]
Ah, crazy. Will fix ASAIC

**Comment by chrisjdavis** [comment]
This was resolved some time ago.
