### ISSUE TITLE
Post previews don't work

### ISSUE THREAD

**Issue by michaeltwofish** [habari/hpo#22]
Previewing a draft post loads does not load the post.

**Comment by ringmaster** [comment]
Practically everything in the admin in 0.10 is in flux at the moment.  It's not surprising that the preview doesn't work, especially if it was originally based on shifty javascript and shoddy CSS classes/ids.

**Comment by ringmaster** [comment]
Then again, I thought that your oddly-worded issue meant one thing (that the preview link didn't cause the correct post to appear), but I now guess you meant something else, because that works for me.  ?

**Comment by ringmaster** [comment]
Duh.  Just saw that this is a HPO theme issue.  Please disregard my apparently rampant stroke symptoms.
