### ISSUE TITLE
Menu becomes misplaced

### ISSUE THREAD

**Issue by michaeltwofish** [habari/hpo#6]
The menu can become displaced so that it appears below the fixed menu bar.

![Misplaced image](http://content.screencast.com/users/michael.twofish/folders/Jing/media/ad9ba3de-966c-404a-acbc-d3b23afbf6ad/00000080.png)

I can't work out how it happened, but I did resize narrow enough to make the navigation icon appear.

**Comment by chrisjdavis** [comment]
could you give me a rundown on your environment? Normal stuff, browser and version, OS, etc.

**Comment by michaeltwofish** [comment]
Sorry, I did mean to include that. Latest chrome on Mountain Lion.

On Thursday, April 4, 2013, Chris J. Davis wrote:

> could you give me a rundown on your environment? Normal stuff, browser and
> version, OS, etc.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/habari/hpo/issues/6#issuecomment-15865448
> .

## 

Michael C. Harris
http://twofishcreative.com/michael/blog
IRC: michaeltwofish #habari

**Comment by michaeltwofish** [comment]
Reproduction steps:
- Resize your browser to the narrowest media query rule width to reveal the menu icon and hide the menu.
- Click the menu icon. The url is now http://habariproject.org/en/#menu.
- Resize to a wider media query rule width, and behold the misplace menu.

Alternatively, just go to http://habariproject.org/en/#menu.

This may get fixed as a result of fixing #3.

**Comment by chrisjdavis** [comment]
I believe this has been addressed as well.
