### ISSUE TITLE
Addon links are difficult to see

### ISSUE THREAD

**Issue by michaeltwofish** [habari/hpo#7]
On the addons page, it's difficult to see what's a link. There's no indication that something is a link and only a very subtle colour change on hover, which obviously doesn't help for touch devices..

**Comment by miklb** [comment]
Actually, links in text on other pages suffer from this as well. See the download page as an example.

**Comment by chrisjdavis** [comment]
I have pushed out a color change for links, should be easier to distinguish now.

**Comment by chrisjdavis** [comment]
Closing this, since it is pretty obvious now what a link is and isn't.
